### ISSUE TITLE
Addtional info

### ISSUE THREAD

**Issue by lfom** [NotTheMessiah95/plymouth-pop-black#1]
Hi! Thanks for the theme. As I am using systemd-boot, it only started to show in the boot when I updated the initramfs using the command:

`sudo update-initramfs -k all -u`

You may want to add this to the ReadMe. Also, the Pop icon is kinda blurry, this is the one I use, from my rEFInd theme:
![watermark](https://user-images.githubusercontent.com/15659999/81249827-01043080-8ff6-11ea-9e06-f5c1899f680c.png)

Regards

**Comment by conor-walker** [comment]
Hey, thanks for the feedback! I just boot directly from the EFI stub, so haven't experienced that - I'll add that in the readme in case someone else can make use of it :)
The icon isn't the best, I agree - I just put it together quickly in GIMP to have something in black and white to fit the aesthetic but alas, I've never used GIMP before. I find it's actually quicker on my system at least without an icon, but maybe I'll include a high quality one that can just be removed if needed.
Cheers!
